### PR TITLE
Add Replicate demo and API 

### PR DESCRIPTION
**Pull request by chenxwh**
Hey @ToTheBeginning   ! 👋 

This pull request makes it possible to run your model inside a Docker environment, which makes it easier for other people to run it.  We're using an open source tool called [Cog](https://github.com/replicate/cog) to make this process easier.

This also means we can make a web page where other people can run your model! View it here: https://replicate.com/cjwbw/animesr

Replicate also have an API, so people can easily run your model from their code:

```python
import replicate
model = replicate.models.get("cjwbw/animesr")
output = model.predict(video="...")
```

There are already a few TencentARC models on Replicate [here](https://replicate.com/tencentarc). We would also like to transfer AnimeSR to TencentARC replicate account so you can modify and update the page you like. Would you like us to transfer to ownership?

In case you're wondering who I am, I'm from [Replicate](https://replicate.com/home), where we're trying to make machine learning reproducible. We got frustrated that we couldn't run all the really interesting ML work being done. So, we're going round implementing models we like. 😊

### CODE REVIEW

**Comment by ToTheBeginning** [comment]
It looks great, thank you so much for your help!

Yeah, please transfer the ownership to TencentARC so we can modify and update the page~

**Comment by chenxwh** [comment]
Thanks for merging! It is transferred to https://replicate.com/tencentarc/animesr now. To push changes to the page you would need to have your replicate account added to the `tencentarc` org, if you have registered an account (simply with your Github) let me know and I will add you :)

**Comment by ToTheBeginning** [comment]
Hi @chenxwh , Thanks again for your help. 
I have registered an account with my Github (https://replicate.com/tothebeginning), please help me add it under the TencentARC organization.

**Comment by chenxwh** [comment]
Sue, I have just added you to the [TencentARC](https://replicate.com/tencentarc) organization now and you should have write access to the page now!

**Pull request merged**
